### ISSUE TITLE
How do I install this plugin?

### ISSUE THREAD

**Issue by Phlegmethon** [ToxicFrazzles/TShockChestSort#2]
Hello, I'm unsure how to install this plugin and where to put what. Would you mind including this information in the README / description of the plugin?

**Comment by ToxicFrazzles** [comment]
My apologies, I didn't think anybody would find or even want to use this plugin.
I will put together some usage instructions later and look into some of the other issues I've been having with it.

**Comment by Phlegmethon** [comment]
Thank you and no rush! Nothing to apologize for :>

**Comment by ToxicFrazzles** [comment]
I hope the added instructions are enough. If not please let me know.

**Comment by Phlegmethon** [comment]
I managed to get it installed but the /sort and /pausesort commands are not working. I am only getting the message "Invalid command entered. Type /help for a list of valid commands."

**Comment by ToxicFrazzles** [comment]
Just to make sure we're on the same page: the "plugin" is the file called "ChestSort.dll" under the assets list on the release and should be in the ServerPlugins folder like this 
![image](https://github.com/ToxicFrazzles/TShockChestSort/assets/19980075/9fa0b747-3b63-4b42-a3e8-ab99c3182b4c)
I should've made that more clear in the instructions.

The fact it says the commands are invalid leads me to believe the plugin was not loaded at all. If the plugin was installed as above I can't imagine any reasons why that would be the case though.

**Comment by Phlegmethon** [comment]
Pardon me if I'm missing something but I can't seem to find a single .dll file included in the post?

**Comment by ToxicFrazzles** [comment]
Ah that's okay. The .dll file is under "Assets" on the releases page. Just follow [this link](https://github.com/ToxicFrazzles/TShockChestSort/releases) to the list of releases, expand the "Assets" of the latest one and you should be able to see the file.

**Comment by ToxicFrazzles** [comment]
Alternatively here's the file for the current latest release (V1.0.5.1 for TShock 5.2) 
[ChestSort.dll](https://github.com/ToxicFrazzles/TShockChestSort/releases/download/V1.0.5.1/ChestSort.dll)

**Comment by Phlegmethon** [comment]
Ahh, thank you! I'll check if it works now ^^

**Comment by Phlegmethon** [comment]
It works! Thank you so much for your help ^^ Apologies if I was a bit dense -- I never usually use GitHub and find it a bit confusing at times to know where to download things ^^

**Comment by ToxicFrazzles** [comment]
No worries. I'll close this issue for now, but if you need any help using the (very experimental) plugin feel free to reach out 😊
